name: Install and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: 'pip'

    - name: Create virtual environment
      run: |
        make venv

    - name: Install project
      run: |
        make install-test-dependencies

    - name: Run tests
      run: |
        make test